version: '2.1'

services:
  portainer:
    image: portainer/portainer:1.20.0
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
volumes:
  portainer_data:
    name: portainer_portainer_data
